apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      name: employee
      labels:
        app: employee
    spec:
      containers:
        - name: employee-service
          image: khaydev1/employee-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: postgres_user
              valueFrom:
                secretKeyRef:
                  name: employee-secret
                  key: database_username
            - name: postgres_password
              valueFrom:
                secretKeyRef:
                  name: employee-secret
                  key: database_password
            - name: employee_db_url
              valueFrom:
                configMapKeyRef:
                  name: employee-configmap
                  key: database_url
            - name: department_service_uri
              value: department-service
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer



