server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${postgres_user}
    password: ${postgres_password}
    url: ${db_url}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true