apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-deployment
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      name: department
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: khaydev1/department-service:2.0.0
          imagePullPolicy: Always
          env:
            - name: postgres_user
              valueFrom:
                secretKeyRef:
                  name: department-secret
                  key: database_username
            - name: postgres_password
              valueFrom:
                secretKeyRef:
                  name: department-secret
                  key: database_password
            - name: db_url
              valueFrom:
                configMapKeyRef:
                  name: department-configmap
                  key: database_url
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  selector:
    app: department
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer

