pipeline {
    agent any
    //We can use the environment block to set environment variables
    environment {
        KEY = "Value"
    }
     parameters {
            string(name: 'ENVIRONMENT', description: 'Select the environment', defaultValue: 'dev')
            choice(name: 'BRANCH', choices: ['master', 'develop', 'feature'], description: 'Select the branch to build')
            booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run tests during the build')
            file(name: 'CONFIG_FILE', description: 'Upload a configuration file')
        }
    stages {

        stage('Build') {
            steps {
                echo 'Building.. Current Build ID is ${env.BUILD_ID}'
            }
        }

        stage('Test') {
            when {
                expression { params.RUN_TESTS }
            }
            steps {
                echo "Running tests..."
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying.. Jenkins Url is ${env.JENKINS_URL}'
            }
        }
    }
}
